baseuri = "/code/jsxm/xm/";  // http://a1k0n-pub.s3-website-us-west-1.amazonaws.com/xm/";
xmuris = [
  ["Zalza - my dirty old kamel", "kamel.xm"],
  ["Zalza - interc00ler", "interc00ler.xm"],
  ["Lizardking - Claustrophobia", "Claustrophobia.xm"],
  ["Lizardking - Transatlantic", "transatlantic.xm"],
  ["Lizardking - Bosvedjan Jam", "bosvedjan.xm"],
  ["xyce - ne pas", "nepas.xm"],
  ["Jugi - Onward", "onward.xm"],
  ["Dubmood - LUCiD Keygen chip", 'db_keygen.xm']
];

/*
'xm/Dubmood/db_beat7.xm',
'xm/Dubmood/db_core.xm',
'xm/Dubmood/db_cro1.xm',
'xm/Dubmood/db_cydon.xm',
'xm/Dubmood/db_daddy.xm',
'xm/Dubmood/db_elimi.xm',
'xm/Dubmood/db_girl.xm',
'xm/Dubmood/db_ida.xm',
'xm/Dubmood/db_int14.xm',
'xm/Dubmood/db_key2.xm',
'xm/Dubmood/db_key4.xm',
'xm/Dubmood/db_key5.xm',
'xm/Dubmood/db_key6.xm',
'xm/Dubmood/db_key7.xm',
'xm/Dubmood/db_key8.xm',
'xm/Dubmood/db_keygen.xm',
'xm/Dubmood/db_pdx1.xm',
'xm/Dubmood/db_pdx2.xm',
'xm/Dubmood/db_pdx3.xm',
'xm/Dubmood/db_toffe.xm',
'xm/Dubmood/dubmood_josss-starchip.xm',
'xm/Dubmood/flc_doit.xm',
'xm/Dubmood/rfchip01.xm',
'xm/Jugi/onward.xm',
'xm/Lizardking/bosvedjan.xm',
'xm/Lizardking/Claustrophobia.xm',
'xm/Lizardking/transatlantic.xm',
'xm/xyce/nepas.xm',
'xm/xyce/xyce-dans_la_rue.xm',
'xm/xyce/xyce-je_suis_baguette.xm',
'xm/xyce/xyce-nospetitesfemmes.xm',
'xm/xyce/xyce-rainbowdash.xm',
'xm/Zalza/alf2_zalza_edit.xm',
'xm/Zalza/bigmomma.xm',
'xm/Zalza/crusin.xm',
'xm/Zalza/elzalz0.xm',
'xm/Zalza/interc00ler.xm',
'xm/Zalza/kamel.xm',
'xm/Zalza/karatemuffins.xm',
'xm/Zalza/sidmatic.xm',
'xm/Zalza/zalza-tequila_groove.xm',
'xm/Zalza/Zalza_-_Superposition_-_Chasing_The_Clouds.xm',
'xm/Zalza/Zalza_-_Superposition_-_Douchebag_Rumble.xm',
'xm/Zalza/Zalza_-_Superposition_-_Just_Clowning_Around.xm',
'xm/Zalza/Zalza_-_Superposition_-_Lil_Fighter.xm',
'xm/Zalza/Zalza_-_Superposition_-_Love_Is_The_Cure.xm',
'xm/Zalza/Zalza_-_Superposition_-_Magnolia_Bakery.xm',
'xm/Zalza/Zalza_-_Superposition_-_Ms_Bed_Burrito.xm',
'xm/Zalza/Zalza_-_Superposition_-_Remanence_(Intro).xm',
'xm/Zalza/Zalza_-_Superposition_-_Serotonin.xm',
'xm/Zalza/Zalza_-_Superposition_-_The_Lonesome_Droid.xm',
'xm/Zalza/Zalza_-_Superposition_-_Ultraviolet.xm',
'xm/Zalza/Zalza_-_Superposition_-_Waves_Of_Energy.xm',
'xm/Zalza/Zalza_-_Superposition_-_Window_Of_Opportunities.xm',
];
*/
